# Generated by Django 4.2.3 on 2023-07-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_serial_motor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='vehiculo',
            table='vehiculo',
        ),
    ]
